Repository ithaka/apiron, pull requests merged in 2019-04, with the labels that each got.

#41 Include checkbox for changelog in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⛏ chore

#38 Fix dynamic StubEndpoint call (#37)
  CHANGELOG.md
  apiron/client.py
  apiron/endpoint/stub.py
  tests/test_endpoint.py
Labels: 🐛 bug

#40 Simplify imports (#39)
  CHANGELOG.md
  README.md
  apiron/__init__.py
  apiron/endpoint/__init__.py
  apiron/service/__init__.py
  docs/advanced-usage.rst
  docs/getting-started.rst
  tests/service/test_base.py
  tests/service/test_discoverable.py
  tests/test_client.py
  tests/test_endpoint.py
Labels: ✨ enhancement

#44 v2.4.0 release prep
  CHANGELOG.md
  apiron/VERSION
Labels: ⛏ chore

#47 Add release activity to pull request options
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨ enhancement

#48 Introspect path kwargs
  CHANGELOG.md
  README.md
  apiron/client.py
  apiron/endpoint/endpoint.py
  dev-requirements.txt
  docs/advanced-usage.rst
  docs/getting-started.rst
  tests/test_client.py
  tests/test_endpoint.py
Labels: ✨ enhancement

#49 Improve inheritance structure
  CHANGELOG.md
  apiron/service/__init__.py
  apiron/service/base.py
  apiron/service/discoverable.py
  tests/service/test_base.py
Labels: ⛏ chore

#51 Forward the `json` kwarg to requests
  CHANGELOG.md
  apiron/client.py
  tests/test_client.py
Labels: ✨ enhancement

#52 Prep for 2.5.0 release
  CHANGELOG.md
  apiron/VERSION
Labels: ⛏ chore

#55 Add linting stage to Travis CI build
  .github/CONTRIBUTING.md
  .travis.yml
  apiron/__init__.py
  apiron/client.py
  apiron/endpoint/__init__.py
  apiron/endpoint/endpoint.py
  apiron/endpoint/json.py
  apiron/endpoint/stub.py
  apiron/exceptions.py
  apiron/service/__init__.py
  apiron/service/base.py
  apiron/service/discoverable.py
  pyproject.toml
  tests/service/test_base.py
  tests/service/test_discoverable.py
  tests/test_client.py
  tests/test_endpoint.py
Labels: ✨ enhancement

#56 Use pytest.warns for testing warnings
  tests/test_endpoint.py
Labels: ⛏ chore

#57 Replace metaclass behavior with descriptor protocol
  CHANGELOG.md
  apiron/endpoint/endpoint.py
  apiron/endpoint/stub.py
  apiron/service/base.py
Labels: ⛏ chore
