Repository ithaka/apiron, pull requests merged in 2019-06, with the labels that each got.

#58 Provide optional allow_redirects parameter for enabling/disabling HTTP redirection
  CHANGELOG.md
  apiron/client.py
  tests/test_client.py
Labels: ✨ enhancement

#59 Prep for 2.6.0 release
  CHANGELOG.md
  apiron/VERSION
Labels: ⛏ chore

#62 Backward compatibility for ServiceCaller.call() and instantiated services
  CHANGELOG.md
  apiron/endpoint/endpoint.py
  apiron/endpoint/stub.py
  tests/test_endpoint.py
Labels: 🐛 bug

#63 Prep 2.6.1 release
  CHANGELOG.md
  apiron/VERSION
Labels: ⛏ chore

#64 Add test for bug fixed in 2.6.1 for stub endpoints
  CHANGELOG.md
  tests/test_endpoint.py
Labels: ✨ enhancement

#65 Fix condition for deployments from Travis CI (#61)
  .travis.yml
Labels: 🐛 bug

#66 Remove ServiceCaller and path_kwargs vestiges
  CHANGELOG.md
  apiron/__init__.py
  apiron/client.py
  apiron/endpoint/endpoint.py
  apiron/endpoint/stub.py
  docs/api-reference/index.rst
  docs/api-reference/service-client.rst
  docs/getting-started.rst
  docs/index.rst
  docs/upgrade-guide.rst
  tests/test_client.py
  tests/test_endpoint.py
Labels: ✨ enhancement, 📝 docs

#67 Prep for 3.0.0 release
  CHANGELOG.md
  apiron/VERSION
Labels: ⛏ chore

#68 Try allowing deployments when tags are created
  .travis.yml
Labels: ⛏ chore, 🐛 bug
